# include <stdio.h>
# include <conio.h>
void main ()
{
  int no;
    printf("\n Enter no between 1 to 12=");
    scanf("%d",&no);
      if (no == 1 )
      {
      printf("\n January");
      }
      else if (no == 2 )
      {
      printf("\n February");
      }
      else if (no == 3 )
      {
      printf("\n March");
      }
      else if (no == 4 )
      {
      printf("\n April");
      }
      else if (no == 5 )
      {
      printf("\n May");
      }
      else if (no == 6 )
      {
      printf("\n June");
      }
      else if (no == 7 )
      {
      printf("\n July");
      }
      else if (no == 8 )
      {
      printf("\n August");
      }
      else if (no == 9 )
      {
      printf("\n September");
      }
      else if (no == 10 )
      {
      printf("\n October");
      }
      else if (no == 11 )
      {
      printf("\n November");
      }
      else if (no == 12 )
      {
      printf("\n December");
      }
      else
      {
      printf("\n Wrong Number Entered");
      }
      getch();
      }
